# Generated by Django 4.2.3 on 2023-07-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bite_code',
            field=models.CharField(default='f4a9c5d3', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='OFF', max_length=255),
        ),
    ]
