# Generated by Django 4.2.3 on 2023-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_device_bite_code_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bite_code',
            field=models.CharField(default='7d9b5d32', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_info',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
