# Generated by Django 4.2.3 on 2023-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_device_bite_code_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='device',
            name='bite_code',
            field=models.CharField(default='ea5f6eb1', max_length=255),
        ),
    ]
