# Generated by Django 4.2.3 on 2023-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_id_device_user_rename_user_id_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
