# Generated by Django 4.2.4 on 2023-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_info',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
